[project]
name = "pipelex-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepagents>=0.2.0",
    "langchain-openai>=1.0.1",
    "pipelex>=0.14.3",
    "streamlit>=1.51.0",
]
